language: cpp
cache: ccache
sudo: required
dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - clang-3.8
    - build-essential
    - pkg-config
    - cmake
    - libpython-dev python-numpy
    - libboost-all-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update          ; fi

script:
  - bash .travis.sh

env:
  global:
    - MAKEFLAGS="-j 2"
    - CCACHE_SLOPPINESS=pch_defines,time_macros

# gcc is too slow and we have a time limit in Travis CI: selective builds.
matrix:
  include:
  - compiler: gcc
    os: linux
    env: GTSAM_BUILD_UNSTABLE=ON GTSAM_BUILD_EXAMPLES_ALWAYS=ON GTSAM_BUILD_TESTS=OFF
  - compiler: gcc
    os: linux
    env: GTSAM_BUILD_UNSTABLE=OFF GTSAM_BUILD_EXAMPLES_ALWAYS=OFF GTSAM_BUILD_TESTS=ON # gcc too slow for all tests
  - compiler: gcc
    os: linux
    env: GTSAM_BUILD_UNSTABLE=ON GTSAM_BUILD_EXAMPLES_ALWAYS=ON GTSAM_BUILD_TESTS=OFF GCC_VERSION="8"
  - compiler: clang
    os: linux
    env: GTSAM_BUILD_UNSTABLE=ON GTSAM_BUILD_EXAMPLES_ALWAYS=ON GTSAM_BUILD_TESTS=OFF
  - compiler: gcc
    os: osx
    env: GTSAM_BUILD_UNSTABLE=ON GTSAM_BUILD_EXAMPLES_ALWAYS=ON GTSAM_BUILD_TESTS=OFF
  - compiler: clang
    os: osx
    env: GTSAM_BUILD_UNSTABLE=ON GTSAM_BUILD_EXAMPLES_ALWAYS=OFF GTSAM_BUILD_TESTS=ON
